name: fitness_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Icons + UI
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  flutter_screenutil: ^5.9.3

  # Network + Storage
  dio: ^5.9.0
  http: ^1.5.0
  shared_preferences: ^2.5.3

  # State Management
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1

  # Localization
  easy_localization: ^3.0.8

  # Onboarding
  introduction_screen: ^4.0.0

  # Styling
  control_style: ^0.1.0

  # Splash
  flutter_native_splash: ^2.4.4

  # App Icons
  flutter_launcher_icons: ^0.14.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  audioplayers: ^6.4.0
  just_audio: ^0.9.46
  audio_session: ^0.1.25
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.1.0


# Splash Screen Configuration
flutter_native_splash:
  color: "#535864"
  image: "assets/images/helios_logo.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#535864"
    image: "assets/images/helios_logo_android12.png"

# App Icons Configuration
flutter_launcher_icons:
  android: "helios_sports"
  ios: true
  image_path: "assets/images/helios_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/helios_logo.png"
    background_color: "#535864"
    theme_color: "#535864"
  windows:
    generate: true
    image_path: "assets/images/helios_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/helios_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/music/
